# sync-agent-context.ps1
# Syncs AGENTS.md to all agent-specific context files.
# Run this after editing AGENTS.md.
#
# Usage: powershell -File scripts/sync-agent-context.ps1
#
# === SINGLE SOURCE OF TRUTH ===
# AGENTS.md is the master context file for ALL AI assistants:
#
#   AI Assistant     | How it reads AGENTS.md
#   -----------------|-----------------------------------------------
#   Claude (Code)    | Via CLAUDE.md (auto-generated by this script)
#   Cursor           | Via .cursorrules (auto-generated by this script)
#   Windsurf         | Via .windsurfrules (auto-generated by this script)
#   Agent Zero       | Reads AGENTS.md directly via bind mount (no sync needed)
#
# After editing AGENTS.md, run this script to update Claude/Cursor/Windsurf.
# Agent Zero picks up changes instantly — no script needed.

$root = Split-Path -Parent $PSScriptRoot
$source = Join-Path $root "AGENTS.md"

if (-not (Test-Path $source)) {
    Write-Error "AGENTS.md not found at $source"
    exit 1
}

$content = Get-Content $source -Raw

$targets = @{
    "CLAUDE.md" = @"
# Claude Code — Project Context

> This file is auto-generated from ``AGENTS.md``. Edit ``AGENTS.md``, then run:
> ``powershell -File scripts/sync-agent-context.ps1``

<!-- AGENTS_CONTENT_START -->
"@
    ".cursorrules" = @"
# Cursor Rules — Project Context
# Auto-generated from AGENTS.md. Do not edit directly.

"@
    ".windsurfrules" = @"
# Windsurf Rules — Project Context
# Auto-generated from AGENTS.md. Do not edit directly.

"@
}

$footer = @"

<!-- AGENTS_CONTENT_END -->
"@

foreach ($target in $targets.GetEnumerator()) {
    $targetPath = Join-Path $root $target.Key
    $header = $target.Value

    if ($target.Key -eq "CLAUDE.md") {
        $output = $header + $content + $footer
    } else {
        $output = $header + $content
    }

    Set-Content -Path $targetPath -Value $output -Encoding UTF8
    Write-Host "Synced -> $($target.Key)" -ForegroundColor Green
}

Write-Host ""
Write-Host "Done. $($targets.Count) files updated." -ForegroundColor Cyan
Write-Host "Agent Zero reads AGENTS.md directly — no sync needed." -ForegroundColor DarkGray
